# Perfect network configuration for testing (no errors)
stacks:
  - name: alice
    qdevice_typ: generic
    qdevice_cfg:
      num_qubits: 5
      T1: 1000000000
      T2: 1000000000
      init_time: 0
      single_qubit_gate_time: 5
      two_qubit_gate_time: 100
      measure_time: 3700

  - name: bob
    qdevice_typ: generic
    qdevice_cfg:
      num_qubits: 5
      T1: 1000000000
      T2: 1000000000
      init_time: 0
      single_qubit_gate_time: 5
      two_qubit_gate_time: 100
      measure_time: 3700

links:
  - stack1: alice
    stack2: bob
    typ: perfect
    cfg:
      dummy: null

clinks:
  - stack1: alice
    stack2: bob
    typ: instant
