"0.90":
  lambda:
    degrees: [2, 3, 5, 9, 12, 21]
    probabilities: [0.07689, 0.28096, 0.08933, 0.19620, 0.30631, 0.05031]
  rho:
    degrees: [50, 51]
    probabilities: [0.95025, 0.04975]

"0.85":
  lambda:
    degrees: [2, 3, 4, 5, 6, 7, 9, 21]
    probabilities: [0.04528, 0.20537, 0.05878, 0.09427, 0.08454, 0.01176, 0.05137, 0.50015]
  rho:
    degrees: [41, 42]
    probabilities: [0.54204, 0.45795]

"0.80":
  lambda:
    degrees: [2, 3, 6, 7, 8, 17, 26]
    probabilities: [0.09420, 0.18088, 0.11972, 0.08550, 0.09816, 0.07194, 0.34960]
  rho:
    degrees: [29, 30]
    probabilities: [0.58807, 0.41193]

"0.75":
  lambda:
    degrees: [2, 3, 4, 5, 6, 7, 28, 31]
    probabilities: [0.10805, 0.09511, 0.01449, 0.13764, 0.10667, 0.05288, 0.01107, 0.47408]
  rho:
    degrees: [25, 26]
    probabilities: [0.74161, 0.25839]

"0.70":
  lambda:
    degrees: [2, 3, 6, 9, 12, 25, 46, 62, 65, 73]
    probabilities: [0.05343, 0.29406, 0.00896, 0.15571, 0.12189, 0.19872, 0.09572, 0.02741, 0.04056, 0.00354]
  rho:
    degrees: [20, 21]
    probabilities: [0.76922, 0.23077]

"0.65":
  lambda:
    degrees: [2, 3, 4, 5, 9, 13, 15, 21, 51]
    probabilities: [0.10451, 0.15652, 0.08057, 0.00056, 0.12151, 0.10485, 0.10719, 0.00771, 0.31656]
  rho:
    degrees: [2, 15, 16, 21]
    probabilities: [0.000578, 0.06089, 0.47001, 0.46852]

"0.60":
  lambda:
    degrees: [2, 3, 8, 9, 26, 27, 46, 71]
    probabilities: [0.11040, 0.20804, 0.14163, 0.14858, 0.14438, 0.08909, 0.00748, 0.15038]
  rho:
    degrees: [2, 10, 13, 18, 19]
    probabilities: [0.00036, 0.13063, 0.31068, 0.49341, 0.064915]

"0.55":
  lambda:
    degrees: [2, 3, 6, 15, 16, 18, 19, 31]
    probabilities: [0.16880, 0.20994, 0.18095, 0.03846, 0.02635, 0.23454, 0.05815, 0.08280]
  rho:
    degrees: [10, 11]
    probabilities: [0.27631, 0.72369]

"0.50":
  lambda:
    degrees: [2, 3, 4, 5, 6, 8, 9, 10, 11, 14, 15, 17, 47, 49, 55, 56, 57, 58, 59, 66]
    probabilities: [0.14438, 0.19026, 0.01836, 0.00233, 0.04697, 0.05394, 0.05590, 0.01290, 0.00162, 0.06159, 0.13115, 0.01481, 0.00879, 0.00650, 0.00210, 0.00099, 0.11178, 0.06238, 0.05094, 0.02230]
  rho:
    degrees: [10, 12, 13, 14]
    probabilities: [0.47575, 0.46847, 0.02952, 0.02626]