"0.90":
  lambda:
    degrees: [1, 2, 4, 8, 11, 20]
    probabilities: [0.07689, 0.28096, 0.08933, 0.19620, 0.30631, 0.05031]
  rho:
    degrees: [49, 50]
    probabilities: [0.95025, 0.04975]

"0.85":
  lambda:
    degrees: [1, 2, 3, 4, 5, 6, 8, 20]
    probabilities: [0.04528, 0.20537, 0.05878, 0.09427, 0.08454, 0.01176, 0.05137, 0.50015]
  rho:
    degrees: [40, 41]
    probabilities: [0.54204, 0.45795]

"0.80":
  lambda:
    degrees: [1, 2, 5, 6, 7, 16, 25]
    probabilities: [0.09420, 0.18088, 0.11972, 0.08550, 0.09816, 0.07194, 0.34960]
  rho:
    degrees: [28, 29]
    probabilities: [0.58807, 0.41193]

"0.75":
  lambda:
    degrees: [1, 2, 3, 4, 5, 6, 27, 30]
    probabilities: [0.10805, 0.09511, 0.01449, 0.13764, 0.10667, 0.05288, 0.01107, 0.47408]
  rho:
    degrees: [23, 24]
    probabilities: [0.74161, 0.25839]

"0.70":
  lambda:
    degrees: [1, 2, 5, 8, 11, 24, 45, 61, 64, 72]
    probabilities: [0.05343, 0.29406, 0.00896, 0.15571, 0.12189, 0.19872, 0.09572, 0.02741, 0.04056, 0.00354]
  rho:
    degrees: [19, 20]
    probabilities: [0.76922, 0.23077]

"0.65":
  lambda:
    degrees: [1, 2, 3, 4, 8, 12, 14, 20, 50]
    probabilities: [0.10451, 0.15652, 0.08057, 0.00056, 0.12151, 0.10485, 0.10719, 0.00771, 0.31656]
  rho:
    degrees: [1, 14, 15, 20]
    probabilities: [0.000578, 0.06089, 0.47001, 0.46852]

"0.60":
  lambda:
    degrees: [1, 2, 7, 8, 25, 26, 45, 70]
    probabilities: [0.11040, 0.20804, 0.14163, 0.14858, 0.14438, 0.08909, 0.00748, 0.15038]
  rho:
    degrees: [1, 9, 12, 17, 18]
    probabilities: [0.00036, 0.13063, 0.31068, 0.49341, 0.064915]

"0.55":
  lambda:
    degrees: [1, 2, 5, 14, 15, 17, 18, 30]
    probabilities: [0.16880, 0.20994, 0.18095, 0.03846, 0.02635, 0.23454, 0.05815, 0.08280]
  rho:
    degrees: [9, 10]
    probabilities: [0.27631, 0.72369]

"0.50":
  lambda:
    degrees: [1, 2, 3, 4, 5, 7, 8, 9, 10, 13, 14, 16, 46, 48, 54, 55, 56, 57, 58, 65]
    probabilities: [0.14438, 0.19026, 0.01836, 0.00233, 0.04697, 0.05394, 0.05590, 0.01290, 0.00162, 0.06159, 0.13115, 0.01481, 0.00879, 0.00650, 0.00210, 0.00099, 0.11178, 0.06238, 0.05094, 0.02230]
  rho:
    degrees: [9, 11, 12, 13]
    probabilities: [0.47575, 0.46847, 0.02952, 0.02626]
